

def prueba ():
	try:
		# C贸digo que puede lanzar una excepci贸n
		pass
	except Exception as e:
		print(f"Ocurri贸 una excepci贸n: {e}")
    
